showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
checkForUpdates: true
randomMixedPort: false
theme: 0
mixinText: "mixin: # object"
trayScriptManualRunTime: 1736383367892
mixinType: 0
editor: 0
shortcutSystemProxy: Alt+e
shortcutGlobalMode: Alt+g
shortcutRuleMode: Alt+r
shortcutDirectMode: Alt+d
shortcutScriptMode: ""
disableLoadingAdsLink: true
language: 0
profileParsersText: >-
  parsers:
    - url: https://a8puu.no-mad-world.club/link/uZlVBmUTWMlm0btqZ?clash=3&extend=1
      yaml:
        prepend-rules:
          - DOMAIN-SUFFIX,ztoeco.com,DIRECT
          - DOMAIN-SUFFIX,ztocc.com,DIRECT
          - DOMAIN-SUFFIX,zto.com,DIRECT
          - DOMAIN-SUFFIX,qq.com,DIRECT
          - DOMAIN-SUFFIX,dingtalk.com,DIRECT
          - DOMAIN-SUFFIX,aliyun.com,DIRECT
          - DOMAIN-SUFFIX,aliyuncs.com,DIRECT
          - DOMAIN-SUFFIX,zt-express.com,DIRECT
          - DOMAIN-SUFFIX,sogou.com,DIRECT
          - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
          - DOMAIN-SUFFIX,baidu.com,DIRECT
          - DOMAIN-SUFFIX,gov.cn,DIRECT
          - DOMAIN-SUFFIX,gov.com,DIRECT
          - DOMAIN-SUFFIX,taobao.com,DIRECT
          - DOMAIN-SUFFIX,alibaba.com,DIRECT
          - DOMAIN-SUFFIX,alicdn.com,DIRECT
          - DOMAIN-SUFFIX,mmstat.com,DIRECT
          - DOMAIN-SUFFIX,weixin.com,DIRECT
          - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
          - DOMAIN-SUFFIX,weixinbridge.com,DIRECT
          - DOMAIN-SUFFIX,douyin.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinpic.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinstatic.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinvod.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyincdn.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytedance.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,byteimg.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,zijieapi.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytednsdoc.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,ibytedapm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytegoofy.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytescm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytetos.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytetcc.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytegecko.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,amemv.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,doubao.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,zjcdn.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytehwm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
    - url: https://a8puu.no-mad-world.club/link/4dQ3o6rxcOtUSwavM?clash=3&extend=1
      yaml:
        prepend-rules:
          - DOMAIN-SUFFIX,ztoeco.com,DIRECT
          - DOMAIN-SUFFIX,ztocc.com,DIRECT
          - DOMAIN-SUFFIX,zto.com,DIRECT
          - DOMAIN-SUFFIX,qq.com,DIRECT
          - DOMAIN-SUFFIX,dingtalk.com,DIRECT
          - DOMAIN-SUFFIX,aliyun.com,DIRECT
          - DOMAIN-SUFFIX,aliyuncs.com,DIRECT
          - DOMAIN-SUFFIX,zt-express.com,DIRECT
          - DOMAIN-SUFFIX,sogou.com,DIRECT
          - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
          - DOMAIN-SUFFIX,baidu.com,DIRECT
          - DOMAIN-SUFFIX,gov.cn,DIRECT
          - DOMAIN-SUFFIX,gov.com,DIRECT
          - DOMAIN-SUFFIX,taobao.com,DIRECT
          - DOMAIN-SUFFIX,alibaba.com,DIRECT
          - DOMAIN-SUFFIX,alicdn.com,DIRECT
          - DOMAIN-SUFFIX,mmstat.com,DIRECT
          - DOMAIN-SUFFIX,weixin.com,DIRECT
          - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
          - DOMAIN-SUFFIX,weixinbridge.com,DIRECT
          - DOMAIN-SUFFIX,douyin.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinpic.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinstatic.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyinvod.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,douyincdn.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytedance.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,byteimg.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,zijieapi.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytednsdoc.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,ibytedapm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytegoofy.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytescm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytetos.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytetcc.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytegecko.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,amemv.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,doubao.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,zjcdn.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01
          - DOMAIN-SUFFIX,bytehwm.com,ðŸ‡ºðŸ‡² ç¾Žå›½Z01

shortcutShowHideDashboard: ""
trayProxiesStyle: 0
