showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
checkForUpdates: true
randomMixedPort: false
theme: 0
mixinText: "mixin: # object"
trayScriptManualRunTime: 1736383367892
mixinType: 0
editor: 0
shortcutSystemProxy: Alt+e
shortcutGlobalMode: Alt+g
shortcutRuleMode: Alt+r
shortcutDirectMode: Alt+d
shortcutScriptMode: ""
disableLoadingAdsLink: true
language: 0
profileParsersText: >-
  parsers:
    - url: https://a8puu.no-mad-world.club/link/uZlVBmUTWMlm0btq?clash=3&extend=1
      yaml:
        prepend-proxies:
          - name: SELF-USA
            type: ss
            server: 137.184.89.173
            port: 45870
            cipher: aes-256-cfb
            password: G8Uj5D3Sh9aV1cIeFQ[sAy'R%*vd]TB4t.rO
        # append-proxies:
        #   - name: SELF-USA-LAST
        #     type: ss
        #     server: 137.184.89.173
        #     port: 45870
        #     cipher: aes-256-cfb
        #     password: G8Uj5D3Sh9aV1cIeFQ[sAy'R%*vd]TB4t.rO
        commands:
          - proxy-groups.(ğŸ”° é€‰æ‹©èŠ‚ç‚¹).proxies=[]proxyNames
        prepend-rules:
          - DOMAIN-SUFFIX,ztoeco.com,DIRECT
          - DOMAIN-SUFFIX,ztocc.com,DIRECT
          - DOMAIN-SUFFIX,zto.com,DIRECT
          - DOMAIN-SUFFIX,ztosys.com,DIRECT
          - DOMAIN-SUFFIX,zt-express.com,DIRECT
          - DOMAIN-SUFFIX,qq.com,DIRECT
          - DOMAIN-SUFFIX,dingtalk.com,DIRECT
          - DOMAIN-SUFFIX,aliyun.com,DIRECT
          - DOMAIN-SUFFIX,aliyuncs.com,DIRECT
          - DOMAIN-SUFFIX,sogou.com,DIRECT
          - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
          - DOMAIN-SUFFIX,baidu.com,DIRECT
          - DOMAIN-SUFFIX,gov.cn,DIRECT
          - DOMAIN-SUFFIX,gov.com,DIRECT
          - DOMAIN-SUFFIX,taobao.com,DIRECT
          - DOMAIN-SUFFIX,alibaba.com,DIRECT
          - DOMAIN-SUFFIX,alicdn.com,DIRECT
          - DOMAIN-SUFFIX,mmstat.com,DIRECT
          - DOMAIN-SUFFIX,weixin.com,DIRECT
          - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
          - DOMAIN-SUFFIX,weixinbridge.com,DIRECT
          - DOMAIN-SUFFIX,douyin.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,douyinpic.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,douyinstatic.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,douyinvod.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,douyincdn.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytedance.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,byteimg.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,zijieapi.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytednsdoc.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,ibytedapm.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytegoofy.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytescm.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytetos.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytetcc.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytegecko.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,amemv.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,doubao.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,zjcdn.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN-SUFFIX,bytehwm.com,ğŸ‡ºğŸ‡² ç¾å›½Z01
          - DOMAIN,aeef205.r11.cpolar.top,ğŸ‡­ğŸ‡° é¦™æ¸¯Z01
          - PROCESS-NAME,cmd.exe,ğŸ‡­ğŸ‡° é¦™æ¸¯Z01
    - url: https://a8puu.no-mad-world.club/link/4dQ3o6rxcOtUSwav?clash=3&extend=1
      yaml:
        prepend-rules:
          - DOMAIN-SUFFIX,ztoeco.com,DIRECT
          - DOMAIN-SUFFIX,ztocc.com,DIRECT
          - DOMAIN-SUFFIX,zto.com,DIRECT
          - DOMAIN-SUFFIX,ztosys.com,DIRECT
          - DOMAIN-SUFFIX,zt-express.com,DIRECT
          - DOMAIN-SUFFIX,qq.com,DIRECT
          - DOMAIN-SUFFIX,dingtalk.com,DIRECT
          - DOMAIN-SUFFIX,aliyun.com,DIRECT
          - DOMAIN-SUFFIX,aliyuncs.com,DIRECT
          - DOMAIN-SUFFIX,sogou.com,DIRECT
          - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
          - DOMAIN-SUFFIX,baidu.com,DIRECT
          - DOMAIN-SUFFIX,gov.cn,DIRECT
          - DOMAIN-SUFFIX,gov.com,DIRECT
          - DOMAIN-SUFFIX,taobao.com,DIRECT
          - DOMAIN-SUFFIX,alibaba.com,DIRECT
          - DOMAIN-SUFFIX,alicdn.com,DIRECT
          - DOMAIN-SUFFIX,mmstat.com,DIRECT
          - DOMAIN-SUFFIX,weixin.com,DIRECT
          - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
          - DOMAIN-SUFFIX,weixinbridge.com,DIRECT
          - DOMAIN-SUFFIX,douyin.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,douyinpic.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,douyinstatic.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,douyinvod.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,douyincdn.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytedance.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,byteimg.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,zijieapi.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytednsdoc.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,ibytedapm.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytegoofy.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytescm.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytetos.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytetcc.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytegecko.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,amemv.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,doubao.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,zjcdn.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN-SUFFIX,bytehwm.com,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - DOMAIN,aeef205.r11.cpolar.top,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
          - PROCESS-NAME,cmd.exe,ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.2
shortcutShowHideDashboard: ""
trayProxiesStyle: 0
updateProfileThroughClashProxy: false